export const MAJOR_ARCANA = [
  { id: 0, name: "떠돌이 도사", original: "The Fool", image: "/cards/major_00.jpg", upright: "자유로운 시작, 얽매이지 않음, 무한한 가능성", reversed: "무모함, 준비 부족, 현실 도피" },
  { id: 1, name: "술사", original: "The Magician", image: "/cards/major_01.jpg", upright: "강한 의지, 창조력, 주도적인 변화", reversed: "기만, 능력의 남용, 집중력 분산" },
  { id: 2, name: "신녀", original: "The High Priestess", image: "/cards/major_02.jpg", upright: "직관, 숨겨진 비밀, 차분한 통찰력", reversed: "비밀 누설, 감정적 불안, 표면적인 이해" },
  { id: 3, name: "마고할미", original: "The Empress", image: "/cards/major_03.jpg", upright: "풍요, 모성애, 결실을 맺는 안정", reversed: "과보호, 결핍, 낭비와 나태" },
  { id: 4, name: "대장군", original: "The Emperor", image: "/cards/major_04.jpg", upright: "절대적 권위, 책임감, 견고한 기반", reversed: "독재, 융통성 부족, 무너진 규율" },
  { id: 5, name: "고승", original: "The Hierophant", image: "/cards/major_05.jpg", upright: "깨달음, 정신적 지도, 전통과 규범", reversed: "맹신, 편협한 사고, 규칙에 대한 반항" },
  { id: 6, name: "음양", original: "The Lovers", image: "/cards/major_06.jpg", upright: "운명적 결합, 깊은 인연, 중요한 선택", reversed: "관계의 단절, 갈등, 잘못된 선택" },
  { id: 7, name: "호랑이를 탄 장수", original: "The Chariot", image: "/cards/major_07.jpg", upright: "돌진하는 추진력, 승리, 역경의 극복", reversed: "통제력 상실, 맹목적인 돌진, 패배" },
  { id: 8, name: "범을 다루는 자", original: "Strength", image: "/cards/major_08.jpg", upright: "부드러운 카리스마, 인내심, 내면의 힘", reversed: "나약함, 본능에 휘둘림, 자신감 하락" },
  { id: 9, name: "심산유곡의 도인", original: "The Hermit", image: "/cards/major_09.jpg", upright: "내면 탐색, 고독한 성찰, 신중한 칩거", reversed: "현실 도피, 고립, 지나친 폐쇄성" },
  { id: 10, name: "윤회", original: "Wheel of Fortune", image: "/cards/major_10.jpg", upright: "피할 수 없는 운명, 새로운 전환점, 순환", reversed: "불운, 예상치 못한 악재, 흐름의 단절" },
  { id: 11, name: "저승 판관", original: "Justice", image: "/cards/major_11.jpg", upright: "냉철한 판단, 인과응보, 공정한 결단", reversed: "편견, 불리한 판결, 우유부단함" },
  { id: 12, name: "고행자", original: "The Hanged Man", image: "/cards/major_12.jpg", upright: "희생을 통한 깨달음, 관점의 전환, 정체기", reversed: "의미 없는 헛수고, 자기 합리화, 집착" },
  { id: 13, name: "저승사자", original: "Death", image: "/cards/major_13.jpg", upright: "완전한 끝과 새로운 시작, 과거와의 단절", reversed: "끝내지 못한 미련, 변화에 대한 두려움" },
  { id: 14, name: "음양의 조화", original: "Temperance", image: "/cards/major_14.jpg", upright: "타협과 조화, 순조로운 융합, 절제", reversed: "불균형, 극단적인 감정, 소통의 부재" },
  { id: 15, name: "야차", original: "The Devil", image: "/cards/major_15.jpg", upright: "끊기 힘든 유혹, 억압, 물질적 집착", reversed: "족쇄에서 벗어남, 악습의 굴레를 끊음" },
  { id: 16, name: "벼락 맞은 전각", original: "The Tower", image: "/cards/major_16.jpg", upright: "갑작스러운 붕괴, 재난, 피할 수 없는 파국", reversed: "예견된 몰락, 서서히 무너지는 기반" },
  { id: 17, name: "북두칠성", original: "The Star", image: "/cards/major_17.jpg", upright: "어둠 속의 희망, 치유, 영감과 기원", reversed: "절망, 헛된 희망, 기력의 고갈" },
  { id: 18, name: "붉은 달과 구미호", original: "The Moon", image: "/cards/major_18.jpg", upright: "불안, 숨겨진 적, 환영과 기만", reversed: "오해가 풀림, 진실이 드러남, 불안 해소" },
  { id: 19, name: "삼족오", original: "The Sun", image: "/cards/major_19.jpg", upright: "강렬한 생명력, 확고한 성공, 긍정적 에너지", reversed: "빛바랜 성공, 일시적인 침체, 과시" },
  { id: 20, name: "천상의 북소리", original: "Judgement", image: "/cards/major_20.jpg", upright: "과거에 대한 보상, 부활, 최종적인 결단", reversed: "후회, 기회를 놓침, 스스로에 대한 실망" },
  { id: 21, name: "만다라", original: "The World", image: "/cards/major_21.jpg", upright: "완벽한 성취, 하나의 사이클 완성, 해탈", reversed: "미완성, 정체된 세계, 슬럼프" }
];
